-- Stage 7 spec: work-worker offline message store (design §10 离线消息处理).
--
-- mailbox.lua parks messages aimed at an offline recipient and hands the whole
-- backlog over (in order) when they come back. Capped per box, optional TTL.
--
-- Run via: bin/xnet tests/lua/mailbox_spec.lua

local spec = dofile('tests/lua/spec_helper.lua')
local mailbox = dofile('scripts/game/mailbox.lua')

spec.describe('parking and the login hand-off (§10)', function()
    spec.it('parks messages and reports the pending count', function()
        local mb = mailbox.new()
        spec.equal(mb:pending(7), 0, 'an untouched box is empty')
        mb:deliver(7, { from = 1, body = 'hi' })
        mb:deliver(7, { from = 2, body = 'yo' })
        spec.equal(mb:pending(7), 2)
    end)

    spec.it('stamps a monotonic id, arrival ts, and default kind', function()
        local mb = mailbox.new()
        local m1 = mb:deliver(7, { from = 1, body = 'a' }, 100)
        local m2 = mb:deliver(7, { from = 2, body = 'b', kind = 'gift' }, 200)
        spec.equal(m1.id, 1)
        spec.equal(m2.id, 2, 'ids increase')
        spec.equal(m1.ts, 100, 'arrival time recorded')
        spec.equal(m1.kind, 'mail', 'missing kind defaults to mail')
        spec.equal(m2.kind, 'gift', 'explicit kind is preserved')
    end)

    spec.it('drains the whole backlog in FIFO order and clears the box', function()
        local mb = mailbox.new()
        mb:deliver(7, { body = 'first' })
        mb:deliver(7, { body = 'second' })
        mb:deliver(7, { body = 'third' })
        local out = mb:drain(7)
        spec.equal(#out, 3)
        spec.equal(out[1].body, 'first', 'oldest first')
        spec.equal(out[3].body, 'third', 'newest last')
        spec.equal(mb:pending(7), 0, 'drained box is empty')
        spec.equal(#mb:drain(7), 0, 'a second drain yields nothing')
    end)

    spec.it('peek shows the backlog without consuming it', function()
        local mb = mailbox.new()
        mb:deliver(7, { body = 'x' })
        spec.equal(#mb:peek(7), 1)
        spec.equal(mb:pending(7), 1, 'peek did not consume')
    end)

    spec.it('meters each recipient independently', function()
        local mb = mailbox.new()
        mb:deliver(7, { body = 'for 7' })
        mb:deliver(8, { body = 'for 8a' })
        mb:deliver(8, { body = 'for 8b' })
        spec.equal(mb:pending(7), 1)
        spec.equal(mb:pending(8), 2)
        mb:drain(7)
        spec.equal(mb:pending(8), 2, 'draining 7 leaves 8 untouched')
    end)
end)

spec.describe('capacity (§10)', function()
    spec.it('rejects new mail once a box is full', function()
        local mb = mailbox.new({ cap = 2 })
        spec.truthy(mb:deliver(7, { body = 'a' }), '1st fits')
        spec.truthy(mb:deliver(7, { body = 'b' }), '2nd fits')
        local stored, reason = mb:deliver(7, { body = 'c' })
        spec.nil_value(stored, '3rd over cap -> not stored')
        spec.equal(reason, 'mailbox_full')
        spec.equal(mb:pending(7), 2, 'box stays at cap')
    end)
end)

spec.describe('TTL expiry (§10)', function()
    spec.it('keeps a message until its TTL elapses, then drops it', function()
        local mb = mailbox.new({ ttl_ms = 1000 })
        mb:deliver(7, { body = 'a' }, 0)
        spec.equal(mb:pending(7, 999), 1, 'just shy of TTL -> still there')
        spec.equal(mb:pending(7, 1000), 0, 'at TTL -> expired')
    end)

    spec.it('drops expired mail before the capacity check, making room', function()
        local mb = mailbox.new({ cap = 1, ttl_ms = 1000 })
        mb:deliver(7, { body = 'old' }, 0)
        local stored = mb:deliver(7, { body = 'new' }, 1000)
        spec.truthy(stored, 'expired old mail freed the slot')
        spec.equal(mb:pending(7), 1)
        spec.equal(mb:peek(7)[1].body, 'new', 'only the fresh one remains')
    end)

    spec.it('reap drops expired mail across boxes and prunes empties', function()
        local mb = mailbox.new({ ttl_ms = 1000 })
        mb:deliver(7, { body = 'old7' }, 0)
        mb:deliver(8, { body = 'old8' }, 0)
        mb:deliver(8, { body = 'fresh8' }, 500)
        local dropped = mb:reap(1000)
        spec.equal(dropped, 2, 'two messages past TTL at now=1000')
        spec.equal(mb:pending(7), 0, 'box 7 emptied')
        spec.equal(mb:pending(8), 1, 'box 8 keeps the fresh one')
    end)

    spec.it('without a TTL nothing ever expires', function()
        local mb = mailbox.new()
        mb:deliver(7, { body = 'a' }, 0)
        spec.equal(mb:reap(1e9), 0, 'reap is a no-op')
        spec.equal(mb:pending(7, 1e9), 1, 'still there far in the future')
    end)
end)

spec.describe('claiming a single message (§10)', function()
    spec.it('ack removes one message by id and leaves the rest', function()
        local mb = mailbox.new()
        local a = mb:deliver(7, { body = 'a' })
        mb:deliver(7, { body = 'b' })
        local removed = mb:ack(7, a.id)
        spec.equal(removed.body, 'a', 'returns the claimed message')
        spec.equal(mb:pending(7), 1, 'the other one stays')
        spec.equal(mb:peek(7)[1].body, 'b')
    end)

    spec.it('ack on an unknown id or box is a no-op', function()
        local mb = mailbox.new()
        mb:deliver(7, { body = 'a' })
        spec.nil_value(mb:ack(7, 999), 'unknown id')
        spec.nil_value(mb:ack(8, 1), 'unknown recipient')
        spec.equal(mb:pending(7), 1)
    end)
end)

local failures = spec.finish()

return {
    __init = function()
        if failures > 0 then
            os.exit(1)
        end
        xthread.stop(0)
    end,
}
