package.path = 'scripts/?.lua;' .. package.path
local spec=dofile('tests/lua/spec_helper.lua')
local json=require('xutils')
local auth=require('xagent.auth.chatgpt')
local httpcodec=dofile('scripts/core/share/xhttp_codec.lua')
local saved, writes
local function reset(value)
    auth.cancel(); saved=value; writes=0
    auth.set_storage({load=function() return saved end,save=function(v) saved=v;writes=writes+1;return true end})
end
local function token(body) return nil,{status=200,body=json.json_pack(body)} end
spec.describe('ChatGPT authentication',function()
    spec.it('matches public-client PKCE authorization and token exchange',function()
        reset()
        local url=auth.begin('socks5://localhost:1080')
        local q=httpcodec.parse_query(url:match('%?(.*)'))
        spec.equal(q.code_challenge_method,'S256');spec.equal(q.scope,'openid profile email offline_access')
        spec.equal(q.redirect_uri,'http://localhost:1455/auth/callback')
        local v=auth.finish({state=q.state,code='test-code'},function(opts)
            local body=httpcodec.parse_query(opts.body)
            spec.equal(body.grant_type,'authorization_code');spec.equal(body.client_secret,nil)
            spec.equal(#body.code_verifier,64);spec.equal(opts.proxy,'socks5://localhost:1080')
            return token({access_token='test-access',refresh_token='test-refresh',expires_in=100})
        end)
        spec.equal(v.access_token,'test-access');spec.equal(writes,1)
        spec.equal(pcall(auth.finish,{state=q.state,code='replay'}),false)
    end)
    spec.it('rejects wrong state without consuming the real login',function()
        reset();local url=auth.begin();local q=httpcodec.parse_query(url:match('%?(.*)'))
        spec.equal(pcall(auth.finish,{state='wrong',code='code'}),false)
        auth.finish({state=q.state,code='code'},function() return token({access_token='a',refresh_token='r'}) end)
        spec.equal(writes,1)
    end)
    spec.it('rejects expired login and supports cancellation',function()
        reset();local url=auth.begin(nil,10);local q=httpcodec.parse_query(url:match('%?(.*)'))
        spec.equal(pcall(auth.finish,{state=q.state,code='x'},nil,311),false)
        auth.cancel();spec.equal(pcall(auth.finish,{state=q.state,code='x'}),false)
    end)
    spec.it('preserves refresh token when refresh response omits it',function()
        reset({access_token='old',refresh_token='refresh',expires_at=0,account_id='acct'})
        local v=auth.ensure(nil,function(opts)
            spec.contains(opts.body,'grant_type=refresh_token')
            return token({access_token='new',expires_in=3600})
        end,100)
        spec.equal(v.refresh_token,'refresh');spec.equal(v.account_id,'acct');spec.equal(v.expires_at,3700)
    end)
    spec.it('shares a single refresh across suspended callers',function()
        reset({access_token='old',refresh_token='refresh',expires_at=0})
        local calls,a,b=0
        local transport=function() calls=calls+1;coroutine.yield();return token({access_token='new',refresh_token='rotated'}) end
        local c1=coroutine.create(function() a=auth.ensure(nil,transport) end)
        local c2=coroutine.create(function() b=auth.ensure(nil,transport) end)
        assert(coroutine.resume(c1));assert(coroutine.resume(c2));spec.equal(calls,1)
        assert(coroutine.resume(c1));spec.equal(a.refresh_token,'rotated');spec.equal(b.refresh_token,'rotated')
        spec.equal(writes,1)
    end)
    spec.it('propagates refresh failures without replacing stored credentials',function()
        reset({access_token='old',refresh_token='refresh',expires_at=0})
        local ok=pcall(auth.ensure,nil,function() return nil,{status=400,body='{"error":"invalid_grant"}'} end)
        spec.equal(ok,false);spec.equal(saved.refresh_token,'refresh');spec.equal(writes,0)
    end)
    spec.it('extracts account metadata from returned JWT claims',function()
        local jwt='e30.'..json.base64url_encode(json.json_pack({email='test@example.invalid',
            ['https://api.openai.com/auth']={chatgpt_account_id='acct'}}))..'.test'
        local value=auth.credentials({access_token='a',refresh_token='r',id_token=jwt},nil,100)
        spec.equal(value.account_id,'acct');spec.equal(value.email,'test@example.invalid')
    end)
    spec.it('does not save an exchange after cancellation',function()
        reset();local url=auth.begin();local q=httpcodec.parse_query(url:match('%?(.*)'))
        local ok=pcall(auth.finish,{state=q.state,code='x'},function()
            auth.cancel();return token({access_token='a',refresh_token='r'})
        end)
        spec.equal(ok,false);spec.equal(writes,0)
    end)
    spec.it('allows asynchronous token transport to suspend and resume',function()
        reset();local url=auth.begin();local q=httpcodec.parse_query(url:match('%?(.*)'))
        local co=coroutine.create(function()
            auth.finish({state=q.state,code='x'},function()
                coroutine.yield('network-pending')
                return token({access_token='a',refresh_token='r'})
            end)
        end)
        local ok, state=coroutine.resume(co)
        spec.truthy(ok);spec.equal(state,'network-pending')
        local done, err=coroutine.resume(co)
        spec.truthy(done, err);spec.equal(saved.access_token,'a')
    end)
end)
local failures=spec.finish()
return {__init=function() if failures>0 then os.exit(1) end;xthread.stop(0) end}
