local spec = dofile('tests/lua/spec_helper.lua')
local u = require('xutils')
local root = 'tests/.xutils-fs-' .. os.time() .. '-' .. math.random(1000000)
assert(u.mkdir_p(root))
spec.describe('native filesystem utilities', function()
    spec.it('creates parents and describes directories and missing paths', function()
        assert(u.mkdir_p(root .. '/a/b'))
        spec.equal(u.stat(root .. '/a/b').type, 'directory')
        spec.equal(u.stat(root .. '/absent').exists, false)
    end)
    spec.it('reports file size and refuses mkdir on a file', function()
        local f = assert(io.open(root .. '/file', 'wb')); assert(f:write('hello')); assert(f:close())
        local info = assert(u.stat(root .. '/file'))
        spec.equal(info.type, 'file'); spec.equal(info.size, 5)
        spec.equal(type(info.mtime), 'number')
        spec.equal(u.mkdir_p(root .. '/file'), nil)
    end)
    spec.it('lists empty directories and reports bounded enumeration', function()
        local entries, truncated = u.list_dir(root, 1)
        spec.equal(#entries, 1); spec.equal(truncated, true)
        local empty, more = u.list_dir(root .. '/a/b')
        spec.equal(#empty, 0); spec.equal(more, false)
        spec.equal(u.list_dir(root .. '/absent'), nil)
    end)
    spec.it('lists entries with the metadata stat reports', function()
        local entries = assert(u.list_dir(root, nil, true))
        local by = {}
        for _, e in ipairs(entries) do by[e.name] = e end
        local st = u.stat(root .. '/file')
        spec.equal(by.file.type, 'file'); spec.equal(by.file.dir, false)
        spec.equal(by.file.size, st.size); spec.equal(by.file.mtime, st.mtime)
        spec.equal(by.a.type, 'directory'); spec.equal(by.a.dir, true)
        spec.equal(u.list_dir(root)[1].size, nil)
    end)
    spec.it('rejects NUL paths and invalid bounds', function()
        spec.equal(pcall(u.stat, root .. '\0outside'), false)
        spec.equal(pcall(u.mkdir_p, root .. '\0outside'), false)
        spec.equal(pcall(u.list_dir, root, 0), false)
    end)
end)
assert(u.rmtree(root))
local failures = spec.finish()
return { __init = function() xthread.stop(failures > 0 and 1 or 0) end }
