-- xpac_app.lua - PAC domain management demo app.
-- Edits ./proxy.pac from Lua through a small HTTP page.

local router = dofile('demo/xhttp_router.lua')
local xutils = require('xutils')

local M = {}

local function to_bool(v, default)
    if v == nil then return default end
    if v == true or v == 1 or v == '1' or v == 'true' or v == 'yes' or v == 'on' then
        return true
    end
    if v == false or v == 0 or v == '0' or v == 'false' or v == 'no' or v == 'off' then
        return false
    end
    return default
end

local PAC_FILE = xutils.get_config('PAC_FILE', 'proxy.pac')
local STATIC_DIR = xutils.get_config('PAC_STATIC_DIR', 'demo/static/xpac')
local WEB_SCHEME = to_bool(xutils.get_config('HTTPS_ENABLE', '1'), true) and 'https' or 'http'
local HTTP_PROXY_HOST = xutils.get_config('PAC_HTTP_PROXY_HOST', '127.0.0.1')
local HTTP_PROXY_PORT = tonumber(xutils.get_config('PAC_HTTP_PROXY_PORT', '7890')) or 7890
local SOCKS5_PROXY_HOST = xutils.get_config('PAC_SOCKS5_PROXY_HOST', '127.0.0.1')
local SOCKS5_PROXY_PORT = tonumber(xutils.get_config('PAC_SOCKS5_PROXY_PORT', '1080')) or 1080

local function response(status, body, content_type)
    return {
        status = status,
        body = body or '',
        headers = {
            ['Content-Type'] = content_type or 'text/plain; charset=utf-8',
            ['Cache-Control'] = 'no-store',
        },
    }
end

local function file_response(path, content_type)
    return {
        status = 200,
        file = path,
        headers = {
            ['Content-Type'] = content_type or 'application/octet-stream',
            ['Cache-Control'] = 'no-store',
        },
    }
end

local function trim(s)
    return tostring(s or ''):gsub('^%s+', ''):gsub('%s+$', '')
end

local function lower(s)
    return string.lower(tostring(s or ''))
end

local function uri_decode(s)
    s = tostring(s or ''):gsub('+', ' ')
    return (s:gsub('%%(%x%x)', function(hex)
        return string.char(tonumber(hex, 16))
    end))
end

local function parse_form(body)
    local out = {}
    for part in tostring(body or ''):gmatch('[^&]+') do
        local eq = part:find('=', 1, true)
        if eq then
            out[uri_decode(part:sub(1, eq - 1))] = uri_decode(part:sub(eq + 1))
        else
            out[uri_decode(part)] = ''
        end
    end
    return out
end

local function read_file(path)
    local f, err = io.open(path, 'rb')
    if not f then return nil, err end
    local data = f:read('*a')
    f:close()
    return data
end

local function write_file(path, data)
    local f, err = io.open(path, 'wb')
    if not f then return false, err end
    f:write(data or '')
    f:close()
    return true
end

local function js_string(s)
    s = tostring(s or '')
    s = s:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\r', '\\r'):gsub('\n', '\\n')
    return '"' .. s .. '"'
end

local function read_rules()
    local data = read_file(PAC_FILE)
    local rules = {}
    if not data or data == '' then
        return rules
    end

    for pattern, proxy in data:gmatch('{%s*pattern%s*:%s*"([^"]+)"%s*,%s*type%s*:%s*"([^"]+)"%s*}') do
        proxy = lower(trim(proxy))
        if proxy == 'http' or proxy == 'socks5' then
            rules[#rules + 1] = {
                pattern = lower(trim(pattern)),
                proxy = proxy,
            }
        end
    end
    return rules
end

local function build_pac(rules)
    local lines = {
        '// Generated by xnet PAC manager.',
        '// Edit through ' .. WEB_SCHEME .. '://127.0.0.1:' .. tostring(xutils.get_config('PAC_WEB_PORT', '18090')) .. '/',
        '',
        'var xnetPacRules = [',
    }

    for _, rule in ipairs(rules) do
        lines[#lines + 1] = string.format('  { pattern: %s, type: %s },',
            js_string(rule.pattern), js_string(rule.proxy))
    end

    lines[#lines + 1] = '];'
    lines[#lines + 1] = 'var xnetHttpProxy = ' .. js_string(string.format('PROXY %s:%d', HTTP_PROXY_HOST, HTTP_PROXY_PORT)) .. ';'
    lines[#lines + 1] = 'var xnetSocks5Proxy = ' .. js_string(string.format('SOCKS5 %s:%d', SOCKS5_PROXY_HOST, SOCKS5_PROXY_PORT)) .. ';'
    lines[#lines + 1] = [[

function FindProxyForURL(url, host) {
  host = String(host || "").toLowerCase();
  for (var i = 0; i < xnetPacRules.length; i++) {
    var rule = xnetPacRules[i];
    if (xnetPacMatch(host, rule.pattern)) {
      if (rule.type === "socks5") return xnetSocks5Proxy;
      return xnetHttpProxy;
    }
  }
  return "DIRECT";
}

function xnetPacMatch(host, pattern) {
  pattern = String(pattern || "").toLowerCase();
  if (!pattern) return false;
  if (typeof shExpMatch === "function" && shExpMatch(host, pattern)) return true;
  if (pattern.charAt(0) === ".") pattern = "*" + pattern;
  if (pattern.indexOf("*") >= 0) {
    var expr = "^" + pattern.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*") + "$";
    return new RegExp(expr).test(host);
  }
  return host === pattern || host.slice(-(pattern.length + 1)) === "." + pattern;
}
]]
    return table.concat(lines, '\n')
end

local function save_rules(rules)
    return write_file(PAC_FILE, build_pac(rules))
end

local function ensure_pac()
    local data = read_file(PAC_FILE)
    if data then return true end
    return save_rules({})
end

local function validate_pattern(pattern)
    pattern = lower(trim(pattern))
    if pattern == '' then
        return nil, 'domain is required'
    end
    if #pattern > 255 then
        return nil, 'domain is too long'
    end
    if pattern:find('%s') or pattern:find('/', 1, true) or
       pattern:find('\\', 1, true) or pattern:find('"', 1, true) or
       pattern:find("'", 1, true) then
        return nil, 'domain cannot contain spaces, slash, backslash, or quotes'
    end
    if not pattern:match('^[%w%*%._%-:]+$') then
        return nil, 'domain contains unsupported characters'
    end
    return pattern
end

local function validate_proxy(proxy)
    proxy = lower(trim(proxy))
    if proxy == '' then
        return 'http'
    end
    if proxy == 'http' or proxy == 'socks5' then
        return proxy
    end
    return nil, 'proxy must be http or socks5'
end

local function add_rule(pattern, proxy)
    local normalized, err = validate_pattern(pattern)
    if not normalized then return false, err end
    proxy, err = validate_proxy(proxy)
    if not proxy then return false, err end

    local rules = read_rules()
    local updated = false
    for _, rule in ipairs(rules) do
        if rule.pattern == normalized then
            rule.proxy = proxy
            updated = true
            break
        end
    end

    if not updated then
        rules[#rules + 1] = { pattern = normalized, proxy = proxy }
    end

    local ok, write_err = save_rules(rules)
    if not ok then return false, tostring(write_err) end
    return true, updated and 'rule updated' or 'rule added'
end

local function delete_rule(pattern)
    local normalized, err = validate_pattern(pattern)
    if not normalized then return false, err end

    local rules = read_rules()
    local out = {}
    local removed = false
    for _, rule in ipairs(rules) do
        if rule.pattern == normalized then
            removed = true
        else
            out[#out + 1] = rule
        end
    end

    if not removed then
        return false, 'rule not found'
    end

    local ok, write_err = save_rules(out)
    if not ok then return false, tostring(write_err) end
    return true, 'rule deleted'
end
local function json_response(status, payload)
    local rules = payload.rules or read_rules()
    local body, err = xutils.json_pack({
        ok = payload.ok ~= false,
        message = payload.message or '',
        pac_file = payload.pac_file or PAC_FILE,
        http_proxy = payload.http_proxy or string.format('%s:%d', HTTP_PROXY_HOST, HTTP_PROXY_PORT),
        socks5_proxy = payload.socks5_proxy or string.format('%s:%d', SOCKS5_PROXY_HOST, SOCKS5_PROXY_PORT),
        count = payload.count or #rules,
        rules = rules,
    })
    if not body then
        return response(500, tostring(err or 'json pack failed') .. '\n')
    end
    return response(status, body, 'application/json; charset=utf-8')
end

router.reset({
    file_response = file_response,
    log_prefix = 'XPAC',
    not_found = function()
        return response(404, 'not found\n')
    end,
})

M.route = router.reg
M.router = router

router.reg_path(STATIC_DIR, { index = 'index.html', index_route = '/' })

router.reg('get', '/proxy.pac', function()
    ensure_pac()
    return file_response(PAC_FILE, 'application/x-ns-proxy-autoconfig; charset=utf-8')
end)

router.reg('get', '/api/rules', function()
    ensure_pac()
    return json_response(200, { ok = true, message = 'ok' })
end)

router.reg('post', '/api/rules', function(req)
    local form = parse_form(req.body)
    local ok, msg = add_rule(form.pattern or form.domain, form.proxy)
    return json_response(ok and 200 or 400, { ok = ok, message = msg })
end)

router.reg('post', '/api/rules/delete', function(req)
    local form = parse_form(req.body)
    local ok, msg = delete_rule(form.pattern or form.domain)
    return json_response(ok and 200 or 400, { ok = ok, message = msg })
end)

function M.handle(req)
    return router.handle(req)
end

return M
