-- xpac_app.lua - PAC domain management demo app.
-- Edits ./proxy.pac from Lua through a small HTTP page.

local M = {}

local PAC_FILE = xnet.get_config('PAC_FILE', 'proxy.pac')
local INDEX_FILE = xnet.get_config('PAC_INDEX_FILE', 'demo/xpac_index.html')
local HTTP_PROXY_HOST = xnet.get_config('PAC_HTTP_PROXY_HOST', '127.0.0.1')
local HTTP_PROXY_PORT = tonumber(xnet.get_config('PAC_HTTP_PROXY_PORT', '7890')) or 7890
local SOCKS5_PROXY_HOST = xnet.get_config('PAC_SOCKS5_PROXY_HOST', '127.0.0.1')
local SOCKS5_PROXY_PORT = tonumber(xnet.get_config('PAC_SOCKS5_PROXY_PORT', '1080')) or 1080

local function response(status, body, content_type)
    return {
        status = status,
        body = body or '',
        headers = {
            ['Content-Type'] = content_type or 'text/plain; charset=utf-8',
            ['Cache-Control'] = 'no-store',
        },
    }
end

local function file_response(path, content_type)
    return {
        status = 200,
        file = path,
        headers = {
            ['Content-Type'] = content_type or 'application/octet-stream',
            ['Cache-Control'] = 'no-store',
        },
    }
end

local function trim(s)
    return tostring(s or ''):gsub('^%s+', ''):gsub('%s+$', '')
end

local function lower(s)
    return string.lower(tostring(s or ''))
end

local function uri_decode(s)
    s = tostring(s or ''):gsub('+', ' ')
    return (s:gsub('%%(%x%x)', function(hex)
        return string.char(tonumber(hex, 16))
    end))
end

local function parse_form(body)
    local out = {}
    for part in tostring(body or ''):gmatch('[^&]+') do
        local eq = part:find('=', 1, true)
        if eq then
            out[uri_decode(part:sub(1, eq - 1))] = uri_decode(part:sub(eq + 1))
        else
            out[uri_decode(part)] = ''
        end
    end
    return out
end

local function json_string(s)
    s = tostring(s or '')
    s = s:gsub('[\\"%z\1-\31]', function(ch)
        if ch == '\\' then return '\\\\' end
        if ch == '"' then return '\\"' end
        if ch == '\n' then return '\\n' end
        if ch == '\r' then return '\\r' end
        if ch == '\t' then return '\\t' end
        return string.format('\\u%04x', string.byte(ch))
    end)
    return '"' .. s .. '"'
end

local function json_rules(payload)
    local rows = {}
    for _, rule in ipairs(payload.rules or {}) do
        rows[#rows + 1] = string.format(
            '{"pattern":%s,"proxy":%s}',
            json_string(rule.pattern),
            json_string(rule.proxy)
        )
    end

    return string.format(
        '{"ok":%s,"message":%s,"pac_file":%s,"http_proxy":%s,"socks5_proxy":%s,"count":%d,"rules":[%s]}',
        payload.ok == false and 'false' or 'true',
        json_string(payload.message or ''),
        json_string(PAC_FILE),
        json_string(string.format('%s:%d', HTTP_PROXY_HOST, HTTP_PROXY_PORT)),
        json_string(string.format('%s:%d', SOCKS5_PROXY_HOST, SOCKS5_PROXY_PORT)),
        #(payload.rules or {}),
        table.concat(rows, ',')
    )
end

local function read_file(path)
    local f, err = io.open(path, 'rb')
    if not f then return nil, err end
    local data = f:read('*a')
    f:close()
    return data
end

local function write_file(path, data)
    local f, err = io.open(path, 'wb')
    if not f then return false, err end
    f:write(data or '')
    f:close()
    return true
end

local function js_string(s)
    s = tostring(s or '')
    s = s:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\r', '\\r'):gsub('\n', '\\n')
    return '"' .. s .. '"'
end

local function read_rules()
    local data = read_file(PAC_FILE)
    local rules = {}
    if not data or data == '' then
        return rules
    end

    for pattern, proxy in data:gmatch('{%s*pattern%s*:%s*"([^"]+)"%s*,%s*type%s*:%s*"([^"]+)"%s*}') do
        proxy = lower(trim(proxy))
        if proxy == 'http' or proxy == 'socks5' then
            rules[#rules + 1] = {
                pattern = lower(trim(pattern)),
                proxy = proxy,
            }
        end
    end
    return rules
end

local function build_pac(rules)
    local lines = {
        '// Generated by xnet PAC manager.',
        '// Edit through http://127.0.0.1:' .. tostring(xnet.get_config('PAC_WEB_PORT', '18090')) .. '/',
        '',
        'var xnetPacRules = [',
    }

    for _, rule in ipairs(rules) do
        lines[#lines + 1] = string.format('  { pattern: %s, type: %s },',
            js_string(rule.pattern), js_string(rule.proxy))
    end

    lines[#lines + 1] = '];'
    lines[#lines + 1] = 'var xnetHttpProxy = ' .. js_string(string.format('PROXY %s:%d', HTTP_PROXY_HOST, HTTP_PROXY_PORT)) .. ';'
    lines[#lines + 1] = 'var xnetSocks5Proxy = ' .. js_string(string.format('SOCKS5 %s:%d', SOCKS5_PROXY_HOST, SOCKS5_PROXY_PORT)) .. ';'
    lines[#lines + 1] = [[

function FindProxyForURL(url, host) {
  host = String(host || "").toLowerCase();
  for (var i = 0; i < xnetPacRules.length; i++) {
    var rule = xnetPacRules[i];
    if (xnetPacMatch(host, rule.pattern)) {
      if (rule.type === "socks5") return xnetSocks5Proxy;
      return xnetHttpProxy;
    }
  }
  return "DIRECT";
}

function xnetPacMatch(host, pattern) {
  pattern = String(pattern || "").toLowerCase();
  if (!pattern) return false;
  if (typeof shExpMatch === "function" && shExpMatch(host, pattern)) return true;
  if (pattern.charAt(0) === ".") pattern = "*" + pattern;
  if (pattern.indexOf("*") >= 0) {
    var expr = "^" + pattern.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*") + "$";
    return new RegExp(expr).test(host);
  }
  return host === pattern || host.slice(-(pattern.length + 1)) === "." + pattern;
}
]]
    return table.concat(lines, '\n')
end

local function save_rules(rules)
    return write_file(PAC_FILE, build_pac(rules))
end

local function ensure_pac()
    local data = read_file(PAC_FILE)
    if data then return true end
    return save_rules({})
end

local function validate_pattern(pattern)
    pattern = lower(trim(pattern))
    if pattern == '' then
        return nil, 'domain is required'
    end
    if #pattern > 255 then
        return nil, 'domain is too long'
    end
    if pattern:find('%s') or pattern:find('/', 1, true) or
       pattern:find('\\', 1, true) or pattern:find('"', 1, true) or
       pattern:find("'", 1, true) then
        return nil, 'domain cannot contain spaces, slash, backslash, or quotes'
    end
    if not pattern:match('^[%w%*%._%-:]+$') then
        return nil, 'domain contains unsupported characters'
    end
    return pattern
end

local function validate_proxy(proxy)
    proxy = lower(trim(proxy))
    if proxy == '' then
        return 'http'
    end
    if proxy == 'http' or proxy == 'socks5' then
        return proxy
    end
    return nil, 'proxy must be http or socks5'
end

local function add_rule(pattern, proxy)
    local normalized, err = validate_pattern(pattern)
    if not normalized then return false, err end
    proxy, err = validate_proxy(proxy)
    if not proxy then return false, err end

    local rules = read_rules()
    local updated = false
    for _, rule in ipairs(rules) do
        if rule.pattern == normalized then
            rule.proxy = proxy
            updated = true
            break
        end
    end

    if not updated then
        rules[#rules + 1] = { pattern = normalized, proxy = proxy }
    end

    local ok, write_err = save_rules(rules)
    if not ok then return false, tostring(write_err) end
    return true, updated and 'rule updated' or 'rule added'
end

local function delete_rule(pattern)
    local normalized, err = validate_pattern(pattern)
    if not normalized then return false, err end

    local rules = read_rules()
    local out = {}
    local removed = false
    for _, rule in ipairs(rules) do
        if rule.pattern == normalized then
            removed = true
        else
            out[#out + 1] = rule
        end
    end

    if not removed then
        return false, 'rule not found'
    end

    local ok, write_err = save_rules(out)
    if not ok then return false, tostring(write_err) end
    return true, 'rule deleted'
end
local function json_response(status, payload)
    payload.rules = payload.rules or read_rules()
    return response(status, json_rules(payload), 'application/json; charset=utf-8')
end

local routes = {}

local function route(method, path, handler)
    method = string.upper(tostring(method or ''))
    routes[method] = routes[method] or {}
    routes[method][path] = handler
end

M.route = route

route('GET', '/', function()
    ensure_pac()
    return file_response(INDEX_FILE, 'text/html; charset=utf-8')
end)

route('GET', '/proxy.pac', function()
    ensure_pac()
    return file_response(PAC_FILE, 'application/x-ns-proxy-autoconfig; charset=utf-8')
end)

route('GET', '/api/rules', function()
    ensure_pac()
    return json_response(200, { ok = true, message = 'ok' })
end)

route('POST', '/api/rules', function(req)
    local form = parse_form(req.body)
    local ok, msg = add_rule(form.pattern or form.domain, form.proxy)
    return json_response(ok and 200 or 400, { ok = ok, message = msg })
end)

route('POST', '/api/rules/delete', function(req)
    local form = parse_form(req.body)
    local ok, msg = delete_rule(form.pattern or form.domain)
    return json_response(ok and 200 or 400, { ok = ok, message = msg })
end)

function M.handle(req)
    local method_routes = routes[string.upper(tostring(req.method or ''))]
    local handler = method_routes and method_routes[req.path]
    if handler then
        return handler(req)
    end

    return response(404, 'not found\n')
end

return M
